/**
 * Property-based tests for slugify()
 * Feature: petfarewell-static-site, Property 5: Slug Format Invariant
 *
 * For any page URL generated by the build, the URL path SHALL contain only
 * lowercase letters, digits, hyphens, and forward slashes.
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { slugify } from '../src/lib/slugify';

describe('slugify — Property 5: Slug Format Invariant', () => {
  it('should only contain lowercase letters, digits, hyphens, and forward slashes', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1, maxLength: 200 }), (input) => {
        const result = slugify(input);
        // If result is non-empty, it must match the slug format
        if (result.length > 0) {
          expect(result).toMatch(/^[a-z0-9/][a-z0-9-/]*$|^[a-z0-9/]$/);
        }
      }),
      { numRuns: 200 }
    );
  });

  it('should never contain uppercase letters', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (input) => {
        const result = slugify(input);
        expect(result).not.toMatch(/[A-Z]/);
      }),
      { numRuns: 200 }
    );
  });

  it('should never contain underscores', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (input) => {
        const result = slugify(input);
        expect(result).not.toMatch(/_/);
      }),
      { numRuns: 200 }
    );
  });

  it('should never contain spaces', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (input) => {
        const result = slugify(input);
        expect(result).not.toMatch(/\s/);
      }),
      { numRuns: 200 }
    );
  });

  it('should never contain consecutive hyphens', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (input) => {
        const result = slugify(input);
        expect(result).not.toMatch(/--/);
      }),
      { numRuns: 200 }
    );
  });

  it('should never have leading or trailing hyphens', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (input) => {
        const result = slugify(input);
        if (result.length > 0) {
          expect(result).not.toMatch(/^-/);
          expect(result).not.toMatch(/-$/);
        }
      }),
      { numRuns: 200 }
    );
  });

  it('should be idempotent — slugify(slugify(x)) === slugify(x)', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (input) => {
        const once = slugify(input);
        const twice = slugify(once);
        expect(twice).toBe(once);
      }),
      { numRuns: 200 }
    );
  });

  it('should handle known inputs correctly', () => {
    expect(slugify('Hello World')).toBe('hello-world');
    expect(slugify('pet_cremation')).toBe('pet-cremation');
    expect(slugify('LOS ANGELES')).toBe('los-angeles');
    expect(slugify('café')).toBe('cafe');
    expect(slugify('a--b')).toBe('a-b');
    expect(slugify('')).toBe('');
  });
});
